version: '3.3'

services:

    redis:
      image: redis:5.0.3
      command: ["redis-server", "--appendonly", "yes"]
      ports:
        - "16379:6379"
      networks:
        - my_network
    grafana:
      image: grafana/grafana:5.3.2
      ports:
        - "13000:3000"
      user: "104"
      depends_on:
        - influxdb
      networks:
        - my_network
    influxdb:
      image: influxdb:1.7.2
      ports:
        - "18086:8086"
        - "18090:8090"
      environment:
        - INFLUXDB_DB=locksdb
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=admin
        - INFLUXDB_USER=user
        - INFLUXDB_USER_PASSWORD=user
        - INFLUXDB_REPORTING_DISABLED=false
        - INFLUXDB_HTTP_AUTH_ENABLED=false
      networks:
        - my_network
  #      volumes:
        # Data persistency
        # sudo mkdir -p /srv/docker/influxdb/data
  #        - /srv/docker/influxdb/data:/var/lib/influxdb
    locksapp-diego:
        build:
          context: ./
          dockerfile: Dockerfile
        image: lockaspp
        environment:
#        we need to use here snake case with upper case to translate it to application.properties file
          - APPLICATION_NAME=Diego
          - APPLICATION_LOCKS_SWEETROLL_EXPIRATION_MILLIS=5000
          - SPRING_REDIS_HOST=redis
          - SPRING_REDIS_PORT=6379
          - APP_SWEETROLL_CONSUME_DURATION=3000
          - APP_EATING_PAUSE_DURATION=2000
          - APP_CYCLES=1000
          - APPLICATION_INFLUXDB_URL=http://influxdb:8086
        depends_on:
          - influxdb
        networks:
          - my_network
    locksapp-gorn:
        image: lockaspp:latest
        environment:
       #        we need to use here snake case with upper case to translate it to application.properties file
           - APPLICATION_NAME=Gorn
           - APPLICATION_LOCKS_SWEETROLL_EXPIRATION_MILLIS=5000
           - SPRING_REDIS_HOST=redis
           - SPRING_REDIS_PORT=6379
           - APP_SWEETROLL_CONSUME_DURATION=1000
           - APP_EATING_PAUSE_DURATION=1000
           - APP_CYCLES=1000
           - APPLICATION_INFLUXDB_URL=http://influxdb:8086
        depends_on:
           - influxdb
        networks:
          - my_network
    locksapp-milten:
        image: lockaspp:latest
        environment:
           - APPLICATION_NAME=Milten
           - APPLICATION_LOCKS_SWEETROLL_EXPIRATION_MILLIS=5000
           - SPRING_REDIS_HOST=redis
           - SPRING_REDIS_PORT=6379
           - APP_SWEETROLL_CONSUME_DURATION=4000
           - APP_EATING_PAUSE_DURATION=6000
           - APP_CYCLES=1000
           - APPLICATION_INFLUXDB_URL=http://influxdb:8086
        depends_on:
           - influxdb
        networks:
          - my_network

networks:
  my_network: